Most of this is copy from centaur dotfiles.

** Prerequisite

- GNU Linux, macOS
- git, zsh, curl/wget
- Recommend: GNU Emacs, tmux
- Optional: Vim

** Quickstart

Run this command in the console.

#+begin_src sh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/404cn/dotfiles/main/install.sh)"
#+end_src

or

#+begin_src sh
sh -c "$(wget https://raw.githubusercontent.com/404cn/dotfiles/main/install.sh -O -)"
#+end_src

** Shortcuts

- =Alt-c=: cd into the selected directory.
- =Ctrl-r=: Paste the selected command from history into the command line.
- =Ctrl-t=: Paste the selected file path(s) into the command line.
- =TAB=: To completions.

That's it. Enjoy!

** Tmux

- =`= as prefix, and default =C-b= is unbind.
- =r= to reload configuration.
- =-=, =\= to split window horizontally/vertically.
- =h=, =j=, =k=, =l= and =w=, =a=, =s=, =d= use to select pane.
- =o= to select next pane.
- =H=, =J=, =K=, =L= and =W=, =A=, =S=, =d= use to resize pane.
- =n=, =p=, and =f=, =b= use to select previous/next window.

** Customization

*** ZSH ENV

Add your zsh environments in =~/.zshenv= or =/.zshenv.local=. This is recommended by ZSH officially.
For example:

#+begin_src sh
export PATH=/usr/local/sbin:$PATH
export PATH=$HOME/.rbenv/shims:$PATH
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
#+end_src

*** ZSH local config

Set your personal zsh configurations in =~/.zshrc.local=. For example:

#+begin_src sh
# Oh-my-zsh plugin
zinit snippet OMZP::golang
zinit snippet OMZP::python
zinit snippet OMZP::ruby

# Github plugin
zinit light ptavares/zsh-direnv
#+end_src

See details [[https://github.com/zdharma/zinit][zinit]]

*** Git local config

Set your git configurations in =~/.gitconfig.local=, e.g. user credentials.

#+begin_src sh
[commit]
    # Sign commits using GPG.
    # https://help.github.com/articles/signing-commits-using-gpg/
    gpgsign = true

[user]
    name = John Doe
    email = john.doe@example.com
    signingkey = XXXXXXXX
#+end_src

** Acknowledgements

Related projects: [[https://github.com/ray-g/devstrap][DevStrap]]
